services:
  - type: web
    name: my-flask-app
    env: python
    rootDir: myproject
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
